### ISSUE TITLE
Adding to MS Live calendar does not work.

### ISSUE THREAD

**Issue by Kshatra** [nicolasbeauvais/vue-add-to-calendar#2]
On the demo site (and my test project too) when clicking on "microsoft-calendar" component user gets redirected to MS calendar main page, without "Add to calendar" overlay opened and any related info entered.

**Comment by abdulghafoormahoon** [comment]
I think the problem lies with URL and the param names. I did try with multiple combinations and this one works for me.

The correct url and param names are: 
- https://outlook.live.com/owa/
- startdt
- enddt
- subject
- body
- location

Example URL:
https://outlook.live.com/owa/?rru=addevent&subject=My+New+Question&body=jalsdjfl&startdt=20190115T000000Z&enddt=20190131T000000Z
